name: fdsc
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - numpy=1.23.*
  - pandas=1.5.*
  - scipy=1.9.*
  - pytest=7.1.*
  - rasterio=1.3.*
  - matplotlib=3.6.*
  - geopandas=0.12.*
  - openpyxl
  - numba=0.56.*
  - cudatoolkit
  - colorama
  - pyyaml
  #- xarray=2022.12.*
  #- dask
  - numbagg
  #- rioxarray=0.13.*
  - xlsxwriter=3.0.*
  - georasters

  